apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      containers:
      - name: {{ .Values.component }}
        image: {{ .Values.repo_name }}
